feat(SSOJira): #COE-6 added attributes for specifics groups
CGI-OPEN-ENT-NG/entcore pull request #4
Opened 2023-04-21 15:43 UTC by simonchaval

# Description

Please include a summary of the changes and the related issue.

Added attribute to SSOJira authentication :
- if the user is a "Teacher" or "Personnel", "jira-personnel-ent" group will be added to the response.
- if the user is an "ADML", "jira-administrateur-ent" group will be added to the response.

## Fixes

(Enter here Jira or Redmine ticket(s) links)

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [x] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

1. Describe here the tests you performed
2. Step by step
3. With expected results

You need to test the response with a "Teacher" user, a "Personnel" user and an "ADML" user
- If the user is a "Teacher" or "Personnel" you will see <cas:jira-personnel-ent></cas:jira-personnel-ent>
- If the user is an "ADML" you will see <cas:jira-administrateur-ent></cas:jira-administrateur-ent>

# Reminder

- Security flaws (bros before security holes)
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [ ] All done ! :smiley:

2023-04-21 16:07 UTC, JinDouang approved these changes

2023-04-24 09:34 UTC, BastienBenard commented on auth/src/main/java/org/entcore/auth/services/impl/SSOJira.java
>              handler.handle(new Either.Right<>(result));
Tu n'attends pas la réponse du getUserInfo. C'est voulu ? Je pense que tu devrais mettre cette ligne dans le lambda du getUserInfo

2023-04-25 08:40 UTC, JinDouang requested changes

2023-04-25 08:40 UTC, JinDouang commented on auth/src/main/java/org/entcore/auth/services/impl/SSOJira.java
>              handler.handle(new Either.Right<>(result));
Arf et j'ai validé la PR en plus 👋

je rectifie

2023-04-26 09:44 UTC, merged